name: Build, Push, and Deploy with Minikube

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push App 1
      - name: Build and push App 1
        working-directory: ./app1
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app1:latest -f build/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app1:latest

      # Build and push App 2
      - name: Build and push App 2
        working-directory: ./app2
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app2:latest -f build/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app2:latest

      # Install Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Start Minikube cluster
      - name: Start Minikube
        run: |
          minikube start --driver=docker --nodes=3

      # Label nodes
      - name: Label nodes
        run: |
          kubectl label node minikube-m02 app=app1
          kubectl label node minikube-m03 app=app2

      # Deploy App 1
      - name: Deploy App 1
        working-directory: ./app1/deploy
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # Deploy App 2
      - name: Deploy App 2
        working-directory: ./app2/deploy
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # Deploy Nginx
      - name: Deploy Nginx
        working-directory: ./nginx/deploy
        run: |
          kubectl apply -f nginx-config.yaml
          kubectl apply -f nginx-deployment.yaml

      # Get Minikube IP
      - name: Get Minikube IP
        run: |
          echo "Minikube IP: $(minikube ip)"
